import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "AuraPalm disclaimer — important information about the nature and limitations of our AI-generated readings.",
  robots: { index: false },
};

export default function DisclaimerPage() {
  return (
    <div className="pt-32 pb-16 sm:pt-40 sm:pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="font-display text-4xl font-semibold mb-8">Disclaimer</h1>
        <div className="glass-card rounded-2xl p-8 sm:p-10 space-y-6 text-sm text-text-secondary leading-relaxed">
          <div className="p-4 rounded-xl bg-gold/5 border border-gold/20 mb-6">
            <p className="font-medium text-gold text-base mb-1">Important Notice</p>
            <p>AuraPalm is designed for <strong className="text-text-primary">entertainment and personal reflection only</strong>.</p>
          </div>

          <h2 className="font-display text-xl font-semibold text-text-primary pt-2">1. Not Professional Advice</h2>
          <p>AI-generated readings provided by AuraPalm are <strong className="text-text-primary">not a substitute</strong> for professional advice of any kind, including but not limited to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Medical or health advice</li>
            <li>Financial or investment advice</li>
            <li>Legal counsel</li>
            <li>Psychological or psychiatric treatment</li>
            <li>Therapeutic or counseling services</li>
          </ul>
          <p>If you need professional assistance, please consult a qualified professional in the relevant field.</p>

          <h2 className="font-display text-xl font-semibold text-text-primary pt-4">2. AI-Generated Content</h2>
          <p>All readings are generated by artificial intelligence. While our AI is trained on palmistry and physiognomy traditions, the results are interpretive and should not be taken as factual statements about your character, future, or life circumstances.</p>

          <h2 className="font-display text-xl font-semibold text-text-primary pt-4">3. No Guarantees</h2>
          <p>AuraPalm makes no guarantees, express or implied, about the accuracy, completeness, or usefulness of any reading. Individual experiences may vary. Readings are for entertainment and self-reflection purposes only.</p>

          <h2 className="font-display text-xl font-semibold text-text-primary pt-4">4. User Responsibility</h2>
          <p>By using AuraPalm, you acknowledge that:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>You understand the entertainment nature of this service</li>
            <li>You will not make life decisions based on AI-generated readings</li>
            <li>You will seek professional advice for serious matters</li>
            <li>You are using this service for personal insight and enjoyment</li>
          </ul>

          <div className="p-4 rounded-xl bg-bg-elevated mt-6">
            <p className="text-xs text-text-muted italic">
              If you are experiencing a medical emergency, mental health crisis, or any situation requiring
              immediate professional assistance, please contact your local emergency services immediately.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
